return { -- Useful plugin to show you pending keybinds.
  -- 'folke/which-key.nvim',
  -- event = 'VimEnter',
  -- config = function() -- This is the function that runs, AFTER loading
  --   require('which-key').setup()
  --
  --   -- Document existing key chains
  --   local wk = require('which-key')
  --   wk.add({
  --     { '<leader>c', group = '[C]ode' },
  --     { '<leader>d', group = '[D]ocument' },
  --     { '<leader>r', group = '[R]ename' },
  --     { '<leader>s', group = '[S]earch' },
  --     { '<leader>w', group = '[W]orkspace' },
  --     { '<leader>t', group = '[T]oggle' },
  --     { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
  --   })
  --
  --   wk.add({
  --     { "<leader>ma", "<Plug>(VM-Select-All)<Tab>",    desc = "Select All Words",   mode = { "n" } },
  --     { "<leader>mr", "<Plug>(VM-Start-Regex-Search)", desc = "Start Regex Search", mode = { "n" } },
  --     { "<leader>mp", "<Plug>(VM-Add-Cursor-At-Pos)",  desc = "Add Cursor at Pos",  mode = { "n" } },
  --     { "<leader>mo", "<Plug>(VM-Toggle-Mappings)",    desc = "Toggle Mappings",    mode = { "n" } },
  --   })
  -- end,
}
